### ISSUE TITLE
Experiments in the literature

### ISSUE THREAD

**Issue by zhangjinglin23** [xcist/main#28]
Could you tell me how to run the four experiments in the literature?
And what do the 6.py files in the "examples" file describe respectively? I ran "Sim_Sample_Analyic.py" and "Sim_Sample_XCAT.py" and I couldn't find the file.
Thank you for answering my question.

**Comment by PaulFitzGerald** [comment]
Hi Jingling,

Thanks for your interest in XCIST and in our paper.

Please start here:

https://github.com/xcist/main/tree/master/examples/evaluation

Please read the readme file and the instructions at the top of each .py
file.

Please let me know if you find any issues and if you are able to run the
examples.

Best regards,
Paul

**Comment by zhangjinglin23** [comment]
Thank you for your answer last time.

I'm running experiment one now.
In "mapConfigVariablesToFDK. py" the file, for "rotdir" this parameter is not defined, cause the file "fdk_equiAngle.py" is missing arguments when referring to the function "mapConfigVariablesToFDK()". 
And the error "ValueError: not enough values to unpack (expected 15, got 14)" is displayed.
May I ask how to deal with this problem?
And how do I define the "rotdir" parameter?
Thank you for answering my question.

#fdk_equiAngle.py
def fdk_equiAngle(cfg, prep):
    sid, sdd, nMod, rowSize, modWidth, dectorYoffset, dectorZoffset, \
    fov, imageSize, sliceCount, sliceThickness, centerOffset, startView, **rotdir**, kernelType      \
        = mapConfigVariablesToFDK(cfg)

#mapConfigVariablesToFDK.py
return sid, sdd, nMod, rowSize, modWidth, dectorYoffset, dectorZoffset, \
       fov, imageSize, sliceCount, sliceThickness, centerOffset, startView, kernelType

**Comment by zhangjy-ge** [comment]
Thanks for bringing this bug up. I just fixed it and it should be good now.

**Comment by zhangjinglin23** [comment]
Thank you for your answer last time
When I run experiment 1 and experiment 4, the following errors often occur. I have tried for a long time but still cannot solve them. May I ask how to solve them?
 File "D:\github_model\main-master\reconstruction\pyfiles\fdk_equiAngle.py", line 240, in fdk_equiAngle
    recon.fbp(ct.byref(t))
OSError: exception: access violation writing 0x0000000000000000

Thank you for answering my question.

**Comment by zhangjy-ge** [comment]
This is due to the dll library for Windows is out-of-date. Please try the latest code again and it should not have such errors.

**Comment by zhangjinglin23** [comment]
Thank you for your answer last time.

I'm running experiment 2and experiment 4 now.
I had two problems when I was running these two experiments.

“.json” files are missing in experiment 2
Exception: Cannot find adult_female_50percentile_chest_slab_400.json or adult_female_50percentile_chest_slab_400.json

The “.prep “file could not be generated in experiment 3
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\github_model\\main-master\\examples\\evaluation\\experiment_03_XCAT50_SimAndRecon\\01_01_focalspotWidth4p00_detectorColSize2p00\\01_01_focalspotWidth4p00_detectorColSize2p00.prep'

How can I solve these problems?
Thank you for answering my question.

**Comment by zhangjy-ge** [comment]
for json files you can find them here: https://github.com/xcist/phantoms-voxelized

For problems with prep files, I cannot really see anything for such limited information.

**Comment by zhangjinglin23** [comment]
May I ask if XCIST can generate scattered signals？
